version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    restart: unless-stopped
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8081:8000"
    environment:
      - PYTHONBUFFERED=1
      - ENV=development
      - CORS_ORIGINS=*
      - DYNAMODB_URL=http://dynamodb:8000  
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=yyy
    depends_on: []
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "8082:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
