version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8081:8000"
    environment:
      - PYTHONBUFFERED=1
      - ENV=development
    depends_on: []
  frontend:
    build: ./frontend
    ports:
      - "8082:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
